package com.snh.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fdl.bean.daoBean.BannerData1;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BANNER_DATA1".
*/
public class BannerData1Dao extends AbstractDao<BannerData1, Long> {

    public static final String TABLENAME = "BANNER_DATA1";

    /**
     * Properties of entity BannerData1.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property AdminId = new Property(1, int.class, "AdminId", false, "ADMIN_ID");
        public final static Property Href = new Property(2, String.class, "Href", false, "HREF");
        public final static Property ImageUrl = new Property(3, String.class, "ImageUrl", false, "IMAGE_URL");
        public final static Property OrderBy = new Property(4, int.class, "OrderBy", false, "ORDER_BY");
        public final static Property Default = new Property(5, boolean.class, "Default", false, "DEFAULT");
        public final static Property Audit = new Property(6, boolean.class, "Audit", false, "AUDIT");
    }


    public BannerData1Dao(DaoConfig config) {
        super(config);
    }
    
    public BannerData1Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BANNER_DATA1\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Id
                "\"ADMIN_ID\" INTEGER NOT NULL ," + // 1: AdminId
                "\"HREF\" TEXT," + // 2: Href
                "\"IMAGE_URL\" TEXT," + // 3: ImageUrl
                "\"ORDER_BY\" INTEGER NOT NULL ," + // 4: OrderBy
                "\"DEFAULT\" INTEGER NOT NULL ," + // 5: Default
                "\"AUDIT\" INTEGER NOT NULL );"); // 6: Audit
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BANNER_DATA1\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BannerData1 entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindLong(2, entity.getAdminId());
 
        String Href = entity.getHref();
        if (Href != null) {
            stmt.bindString(3, Href);
        }
 
        String ImageUrl = entity.getImageUrl();
        if (ImageUrl != null) {
            stmt.bindString(4, ImageUrl);
        }
        stmt.bindLong(5, entity.getOrderBy());
        stmt.bindLong(6, entity.getDefault() ? 1L: 0L);
        stmt.bindLong(7, entity.getAudit() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BannerData1 entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindLong(2, entity.getAdminId());
 
        String Href = entity.getHref();
        if (Href != null) {
            stmt.bindString(3, Href);
        }
 
        String ImageUrl = entity.getImageUrl();
        if (ImageUrl != null) {
            stmt.bindString(4, ImageUrl);
        }
        stmt.bindLong(5, entity.getOrderBy());
        stmt.bindLong(6, entity.getDefault() ? 1L: 0L);
        stmt.bindLong(7, entity.getAudit() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BannerData1 readEntity(Cursor cursor, int offset) {
        BannerData1 entity = new BannerData1( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.getInt(offset + 1), // AdminId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Href
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ImageUrl
            cursor.getInt(offset + 4), // OrderBy
            cursor.getShort(offset + 5) != 0, // Default
            cursor.getShort(offset + 6) != 0 // Audit
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BannerData1 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAdminId(cursor.getInt(offset + 1));
        entity.setHref(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImageUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOrderBy(cursor.getInt(offset + 4));
        entity.setDefault(cursor.getShort(offset + 5) != 0);
        entity.setAudit(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BannerData1 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BannerData1 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BannerData1 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
