package com.snh.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fdl.bean.daoBean.AearBean;
import com.fdl.bean.daoBean.BannerBean;
import com.fdl.bean.daoBean.BannerData;
import com.fdl.bean.daoBean.BannerData1;
import com.fdl.bean.daoBean.CommTenant;
import com.fdl.bean.daoBean.CommTenantType;
import com.fdl.bean.daoBean.MainProductBean;
import com.fdl.bean.daoBean.ProductBean;
import com.fdl.bean.daoBean.SupplierBean;
import com.fdl.bean.daoBean.Tips;
import com.fdl.bean.daoBean.Tipsbean;
import com.fdl.bean.SuperMarketBean;

import com.snh.greendao.AearBeanDao;
import com.snh.greendao.BannerBeanDao;
import com.snh.greendao.BannerDataDao;
import com.snh.greendao.BannerData1Dao;
import com.snh.greendao.CommTenantDao;
import com.snh.greendao.CommTenantTypeDao;
import com.snh.greendao.MainProductBeanDao;
import com.snh.greendao.ProductBeanDao;
import com.snh.greendao.SupplierBeanDao;
import com.snh.greendao.TipsDao;
import com.snh.greendao.TipsbeanDao;
import com.snh.greendao.SuperMarketBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aearBeanDaoConfig;
    private final DaoConfig bannerBeanDaoConfig;
    private final DaoConfig bannerDataDaoConfig;
    private final DaoConfig bannerData1DaoConfig;
    private final DaoConfig commTenantDaoConfig;
    private final DaoConfig commTenantTypeDaoConfig;
    private final DaoConfig mainProductBeanDaoConfig;
    private final DaoConfig productBeanDaoConfig;
    private final DaoConfig supplierBeanDaoConfig;
    private final DaoConfig tipsDaoConfig;
    private final DaoConfig tipsbeanDaoConfig;
    private final DaoConfig superMarketBeanDaoConfig;

    private final AearBeanDao aearBeanDao;
    private final BannerBeanDao bannerBeanDao;
    private final BannerDataDao bannerDataDao;
    private final BannerData1Dao bannerData1Dao;
    private final CommTenantDao commTenantDao;
    private final CommTenantTypeDao commTenantTypeDao;
    private final MainProductBeanDao mainProductBeanDao;
    private final ProductBeanDao productBeanDao;
    private final SupplierBeanDao supplierBeanDao;
    private final TipsDao tipsDao;
    private final TipsbeanDao tipsbeanDao;
    private final SuperMarketBeanDao superMarketBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aearBeanDaoConfig = daoConfigMap.get(AearBeanDao.class).clone();
        aearBeanDaoConfig.initIdentityScope(type);

        bannerBeanDaoConfig = daoConfigMap.get(BannerBeanDao.class).clone();
        bannerBeanDaoConfig.initIdentityScope(type);

        bannerDataDaoConfig = daoConfigMap.get(BannerDataDao.class).clone();
        bannerDataDaoConfig.initIdentityScope(type);

        bannerData1DaoConfig = daoConfigMap.get(BannerData1Dao.class).clone();
        bannerData1DaoConfig.initIdentityScope(type);

        commTenantDaoConfig = daoConfigMap.get(CommTenantDao.class).clone();
        commTenantDaoConfig.initIdentityScope(type);

        commTenantTypeDaoConfig = daoConfigMap.get(CommTenantTypeDao.class).clone();
        commTenantTypeDaoConfig.initIdentityScope(type);

        mainProductBeanDaoConfig = daoConfigMap.get(MainProductBeanDao.class).clone();
        mainProductBeanDaoConfig.initIdentityScope(type);

        productBeanDaoConfig = daoConfigMap.get(ProductBeanDao.class).clone();
        productBeanDaoConfig.initIdentityScope(type);

        supplierBeanDaoConfig = daoConfigMap.get(SupplierBeanDao.class).clone();
        supplierBeanDaoConfig.initIdentityScope(type);

        tipsDaoConfig = daoConfigMap.get(TipsDao.class).clone();
        tipsDaoConfig.initIdentityScope(type);

        tipsbeanDaoConfig = daoConfigMap.get(TipsbeanDao.class).clone();
        tipsbeanDaoConfig.initIdentityScope(type);

        superMarketBeanDaoConfig = daoConfigMap.get(SuperMarketBeanDao.class).clone();
        superMarketBeanDaoConfig.initIdentityScope(type);

        aearBeanDao = new AearBeanDao(aearBeanDaoConfig, this);
        bannerBeanDao = new BannerBeanDao(bannerBeanDaoConfig, this);
        bannerDataDao = new BannerDataDao(bannerDataDaoConfig, this);
        bannerData1Dao = new BannerData1Dao(bannerData1DaoConfig, this);
        commTenantDao = new CommTenantDao(commTenantDaoConfig, this);
        commTenantTypeDao = new CommTenantTypeDao(commTenantTypeDaoConfig, this);
        mainProductBeanDao = new MainProductBeanDao(mainProductBeanDaoConfig, this);
        productBeanDao = new ProductBeanDao(productBeanDaoConfig, this);
        supplierBeanDao = new SupplierBeanDao(supplierBeanDaoConfig, this);
        tipsDao = new TipsDao(tipsDaoConfig, this);
        tipsbeanDao = new TipsbeanDao(tipsbeanDaoConfig, this);
        superMarketBeanDao = new SuperMarketBeanDao(superMarketBeanDaoConfig, this);

        registerDao(AearBean.class, aearBeanDao);
        registerDao(BannerBean.class, bannerBeanDao);
        registerDao(BannerData.class, bannerDataDao);
        registerDao(BannerData1.class, bannerData1Dao);
        registerDao(CommTenant.class, commTenantDao);
        registerDao(CommTenantType.class, commTenantTypeDao);
        registerDao(MainProductBean.class, mainProductBeanDao);
        registerDao(ProductBean.class, productBeanDao);
        registerDao(SupplierBean.class, supplierBeanDao);
        registerDao(Tips.class, tipsDao);
        registerDao(Tipsbean.class, tipsbeanDao);
        registerDao(SuperMarketBean.class, superMarketBeanDao);
    }
    
    public void clear() {
        aearBeanDaoConfig.clearIdentityScope();
        bannerBeanDaoConfig.clearIdentityScope();
        bannerDataDaoConfig.clearIdentityScope();
        bannerData1DaoConfig.clearIdentityScope();
        commTenantDaoConfig.clearIdentityScope();
        commTenantTypeDaoConfig.clearIdentityScope();
        mainProductBeanDaoConfig.clearIdentityScope();
        productBeanDaoConfig.clearIdentityScope();
        supplierBeanDaoConfig.clearIdentityScope();
        tipsDaoConfig.clearIdentityScope();
        tipsbeanDaoConfig.clearIdentityScope();
        superMarketBeanDaoConfig.clearIdentityScope();
    }

    public AearBeanDao getAearBeanDao() {
        return aearBeanDao;
    }

    public BannerBeanDao getBannerBeanDao() {
        return bannerBeanDao;
    }

    public BannerDataDao getBannerDataDao() {
        return bannerDataDao;
    }

    public BannerData1Dao getBannerData1Dao() {
        return bannerData1Dao;
    }

    public CommTenantDao getCommTenantDao() {
        return commTenantDao;
    }

    public CommTenantTypeDao getCommTenantTypeDao() {
        return commTenantTypeDao;
    }

    public MainProductBeanDao getMainProductBeanDao() {
        return mainProductBeanDao;
    }

    public ProductBeanDao getProductBeanDao() {
        return productBeanDao;
    }

    public SupplierBeanDao getSupplierBeanDao() {
        return supplierBeanDao;
    }

    public TipsDao getTipsDao() {
        return tipsDao;
    }

    public TipsbeanDao getTipsbeanDao() {
        return tipsbeanDao;
    }

    public SuperMarketBeanDao getSuperMarketBeanDao() {
        return superMarketBeanDao;
    }

}
