package com.snh.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fdl.bean.daoBean.MainProductBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MAIN_PRODUCT_BEAN".
*/
public class MainProductBeanDao extends AbstractDao<MainProductBean, Void> {

    public static final String TABLENAME = "MAIN_PRODUCT_BEAN";

    /**
     * Properties of entity MainProductBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "Id", false, "ID");
        public final static Property Name = new Property(1, String.class, "Name", false, "NAME");
        public final static Property MarketNumber = new Property(2, int.class, "MarketNumber", false, "MARKET_NUMBER");
        public final static Property GoodsImg = new Property(3, String.class, "GoodsImg", false, "GOODS_IMG");
        public final static Property MarketPrice = new Property(4, double.class, "MarketPrice", false, "MARKET_PRICE");
        public final static Property SalesPrice = new Property(5, double.class, "SalesPrice", false, "SALES_PRICE");
        public final static Property DetailUrl = new Property(6, String.class, "DetailUrl", false, "DETAIL_URL");
    }


    public MainProductBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MainProductBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAIN_PRODUCT_BEAN\" (" + //
                "\"ID\" INTEGER NOT NULL ," + // 0: Id
                "\"NAME\" TEXT," + // 1: Name
                "\"MARKET_NUMBER\" INTEGER NOT NULL ," + // 2: MarketNumber
                "\"GOODS_IMG\" TEXT," + // 3: GoodsImg
                "\"MARKET_PRICE\" REAL NOT NULL ," + // 4: MarketPrice
                "\"SALES_PRICE\" REAL NOT NULL ," + // 5: SalesPrice
                "\"DETAIL_URL\" TEXT);"); // 6: DetailUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAIN_PRODUCT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MainProductBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(2, Name);
        }
        stmt.bindLong(3, entity.getMarketNumber());
 
        String GoodsImg = entity.getGoodsImg();
        if (GoodsImg != null) {
            stmt.bindString(4, GoodsImg);
        }
        stmt.bindDouble(5, entity.getMarketPrice());
        stmt.bindDouble(6, entity.getSalesPrice());
 
        String DetailUrl = entity.getDetailUrl();
        if (DetailUrl != null) {
            stmt.bindString(7, DetailUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MainProductBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(2, Name);
        }
        stmt.bindLong(3, entity.getMarketNumber());
 
        String GoodsImg = entity.getGoodsImg();
        if (GoodsImg != null) {
            stmt.bindString(4, GoodsImg);
        }
        stmt.bindDouble(5, entity.getMarketPrice());
        stmt.bindDouble(6, entity.getSalesPrice());
 
        String DetailUrl = entity.getDetailUrl();
        if (DetailUrl != null) {
            stmt.bindString(7, DetailUrl);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MainProductBean readEntity(Cursor cursor, int offset) {
        MainProductBean entity = new MainProductBean( //
            cursor.getInt(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Name
            cursor.getInt(offset + 2), // MarketNumber
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // GoodsImg
            cursor.getDouble(offset + 4), // MarketPrice
            cursor.getDouble(offset + 5), // SalesPrice
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // DetailUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MainProductBean entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMarketNumber(cursor.getInt(offset + 2));
        entity.setGoodsImg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMarketPrice(cursor.getDouble(offset + 4));
        entity.setSalesPrice(cursor.getDouble(offset + 5));
        entity.setDetailUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MainProductBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MainProductBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(MainProductBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
