package com.snh.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.fdl.bean.daoBean.Tipsbean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIPSBEAN".
*/
public class TipsbeanDao extends AbstractDao<Tipsbean, Void> {

    public static final String TABLENAME = "TIPSBEAN";

    /**
     * Properties of entity Tipsbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Title = new Property(0, String.class, "Title", false, "TITLE");
    }


    public TipsbeanDao(DaoConfig config) {
        super(config);
    }
    
    public TipsbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TIPSBEAN\" (" + //
                "\"TITLE\" TEXT);"); // 0: Title
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TIPSBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Tipsbean entity) {
        stmt.clearBindings();
 
        String Title = entity.getTitle();
        if (Title != null) {
            stmt.bindString(1, Title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Tipsbean entity) {
        stmt.clearBindings();
 
        String Title = entity.getTitle();
        if (Title != null) {
            stmt.bindString(1, Title);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Tipsbean readEntity(Cursor cursor, int offset) {
        Tipsbean entity = new Tipsbean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // Title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Tipsbean entity, int offset) {
        entity.setTitle(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Tipsbean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Tipsbean entity) {
        return null;
    }

    @Override
    public boolean hasKey(Tipsbean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
